# GitHub Action - Gerar uma cobra no gráfico de contribuição.
name: Generate snake game

on:
  schedule: # ação executada a cada 24 horas.
    - cron: "* */24 * * *"
  workflow_dispatch: # ação executada automaticamente em Actions.

jobs: # fluxo de trabalho
  build: #construtor
    name: Jobs to update datas # atualizar dados
    runs-on: ubuntu-latest   # executor
    steps: # etapas
      # Animação de cobra
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: karinkau
          svg_out_path: dist/github-contribution-grid-snake2.svg # gerar imagem svg
          snake_color: 'Chartreuse'  # alterar cor da cobra

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
